-- Criação de Views 

-- View da Consulta 2 

CREATE OR REPLACE VIEW vw_infraestrutura_basica_regiao AS
SELECT
  NO_REGIAO,

  COUNT(*) AS total_escolas,

  /* ÁGUA */
  SUM(CASE WHEN IN_AGUA_REDE_PUBLICA = 1 THEN 1 ELSE 0 END) AS agua_sim,
  SUM(CASE WHEN IN_AGUA_REDE_PUBLICA IS NULL THEN 1 ELSE 0 END) AS agua_sem_dado,
  ROUND(
    SUM(CASE WHEN IN_AGUA_REDE_PUBLICA = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0),
    4
  ) AS pct_agua_sim,

  /* ESGOTO */
  SUM(CASE WHEN IN_ESGOTO_REDE_PUBLICA = 1 THEN 1 ELSE 0 END) AS esgoto_sim,
  SUM(CASE WHEN IN_ESGOTO_REDE_PUBLICA IS NULL THEN 1 ELSE 0 END) AS esgoto_sem_dado,
  ROUND(
    SUM(CASE WHEN IN_ESGOTO_REDE_PUBLICA = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0),
    4
  ) AS pct_esgoto_sim,

  /* ENERGIA */
  SUM(CASE WHEN IN_ENERGIA_REDE_PUBLICA = 1 THEN 1 ELSE 0 END) AS energia_sim,
  SUM(CASE WHEN IN_ENERGIA_REDE_PUBLICA IS NULL THEN 1 ELSE 0 END) AS energia_sem_dado,
  ROUND(
    SUM(CASE WHEN IN_ENERGIA_REDE_PUBLICA = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0),
    4
  ) AS pct_energia_sim,

  /* LIXO */
  SUM(CASE WHEN IN_LIXO_SERVICO_COLETA = 1 THEN 1 ELSE 0 END) AS lixo_sim,
  SUM(CASE WHEN IN_LIXO_SERVICO_COLETA IS NULL THEN 1 ELSE 0 END) AS lixo_sem_dado,
  ROUND(
    SUM(CASE WHEN IN_LIXO_SERVICO_COLETA = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0),
    4
  ) AS pct_lixo_sim

FROM microdados_ed_basica
GROUP BY NO_REGIAO;
